In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


a=pd.read_csv(r"/Users/vijay/Downloads/titanic (1)/train.csv")
a['Sex'].replace(['male','female'],[1,2], inplace=True)
a['Age'].replace([np.NaN],[30], inplace=True)
a['SibSp'].replace([np.NaN],[0], inplace=True)
a['Parch'].replace([np.NaN],[0], inplace=True)
a['Fare'].replace([np.NaN],[0], inplace=True)
a['Pclass'].replace([np.NaN],[2], inplace=True)
a['Embarked'].replace(['S','C','Q'],[1,2,3], inplace=True)
a['Embarked'].replace([np.NaN],[2], inplace=True)
a['Survived'].replace([np.NaN],[1], inplace=True)
a

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    2  38.0      1   
2                               Heikkinen, Miss. Laina    2  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    2  35.0      1   
4                             Allen, Mr. William Henry    1  35.0      0   
..                                                 ...  ...   ...    ...   
886                              Montvila, Rev. Juozas    1  27.0      0   
887                       Graham, Miss. Margaret Edith    2  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    2  30.0      1   
889                              Behr, Mr. Karl Howell    1  26.0      0   
890                                Dooley, Mr. Patrick    1  32.0      0   

     Parch            Ticket     Fare Cabin  Embarked  
0        0         A/5 21171   7.2500   NaN       1.0  
1        0          PC 17599  71.2833   C85       2.0  
2        0  STON/O2. 3101282   7.9250   NaN       1.0  
3        0            113803  53.1000  C123       1.0  
4        0            373450   8.0500   NaN       1.0  
..     ...               ...      ...   ...       ...  
886      0            211536  13.0000   NaN       1.0  
887      0            112053  30.0000   B42       1.0  
888      2        W./C. 6607  23.4500   NaN       1.0  
889      0            111369  30.0000  C148       2.0  
890      0            370376   7.7500   NaN       3.0  

[891 rows x 12 columns]

In [2]:
y=np.array(a)[:,1]
y=y.astype('int')


In [3]:
a_reduced=a[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
a_reduced

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         3    1  22.0      1      0   7.2500       1.0
1         1    2  38.0      1      0  71.2833       2.0
2         3    2  26.0      0      0   7.9250       1.0
3         1    2  35.0      1      0  53.1000       1.0
4         3    1  35.0      0      0   8.0500       1.0
..      ...  ...   ...    ...    ...      ...       ...
886       2    1  27.0      0      0  13.0000       1.0
887       1    2  19.0      0      0  30.0000       1.0
888       3    2  30.0      1      2  23.4500       1.0
889       1    1  26.0      0      0  30.0000       2.0
890       3    1  32.0      0      0   7.7500       3.0

[891 rows x 7 columns]

In [4]:
data=np.array(a_reduced)
data

array([[ 3.    ,  1.    , 22.    , ...,  0.    ,  7.25  ,  1.    ],
       [ 1.    ,  2.    , 38.    , ...,  0.    , 71.2833,  2.    ],
       [ 3.    ,  2.    , 26.    , ...,  0.    ,  7.925 ,  1.    ],
       ...,
       [ 3.    ,  2.    , 30.    , ...,  2.    , 23.45  ,  1.    ],
       [ 1.    ,  1.    , 26.    , ...,  0.    , 30.    ,  2.    ],
       [ 3.    ,  1.    , 32.    , ...,  0.    ,  7.75  ,  3.    ]])

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score as cvs
from sklearn.model_selection import KFold

kf=KFold(n_splits=10,shuffle=True,random_state=10)
rfc=RandomForestClassifier(random_state=13,max_depth=4)
scores = cvs(rfc,data,y,cv=kf)
print(scores)
print(scores.mean())


[0.86666667 0.83146067 0.85393258 0.80898876 0.87640449 0.80898876
 0.71910112 0.84269663 0.83146067 0.84269663]
0.8282397003745319


In [6]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(data, y, random_state=20,stratify=y)
rfc=RandomForestClassifier(random_state=14,max_depth=4)
rfc.fit(X_train,y_train)
test_score=rfc.score(X_test,y_test)
train_score=rfc.score(X_train,y_train)
print(train_score)
print(test_score)

0.8323353293413174
0.8475336322869955


In [7]:
rfc.feature_importances_

array([0.17155461, 0.43765819, 0.09714243, 0.05632605, 0.03357597,
       0.17514979, 0.02859296])

In [8]:
a1=pd.read_csv(r"/Users/vijay/Downloads/titanic (1)/test.csv")
a1['Sex'].replace(['male','female'],[1,2], inplace=True)
a1['Age'].replace([np.NaN],[30], inplace=True)
a1['SibSp'].replace([np.NaN],[0], inplace=True)
a1['Parch'].replace([np.NaN],[0], inplace=True)
a1['Fare'].replace([np.NaN],[0], inplace=True)
a1['Pclass'].replace([np.NaN],[2], inplace=True)
a1['Embarked'].replace(['S','C','Q'],[1,2,3], inplace=True)
a1['Embarked'].replace([np.NaN],[2], inplace=True)
a1

PassengerId  Pclass                                          Name  Sex  \
0            892       3                              Kelly, Mr. James    1   
1            893       3              Wilkes, Mrs. James (Ellen Needs)    2   
2            894       2                     Myles, Mr. Thomas Francis    1   
3            895       3                              Wirz, Mr. Albert    1   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    2   
..           ...     ...                                           ...  ...   
413         1305       3                            Spector, Mr. Woolf    1   
414         1306       1                  Oliva y Ocana, Dona. Fermina    2   
415         1307       3                  Saether, Mr. Simon Sivertsen    1   
416         1308       3                           Ware, Mr. Frederick    1   
417         1309       3                      Peter, Master. Michael J    1   

      Age  SibSp  Parch              Ticket      Fare Cabin  Embarked  
0    34.5      0      0              330911    7.8292   NaN         3  
1    47.0      1      0              363272    7.0000   NaN         1  
2    62.0      0      0              240276    9.6875   NaN         3  
3    27.0      0      0              315154    8.6625   NaN         1  
4    22.0      1      1             3101298   12.2875   NaN         1  
..    ...    ...    ...                 ...       ...   ...       ...  
413  30.0      0      0           A.5. 3236    8.0500   NaN         1  
414  39.0      0      0            PC 17758  108.9000  C105         2  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN         1  
416  30.0      0      0              359309    8.0500   NaN         1  
417  30.0      1      1                2668   22.3583   NaN         2  

[418 rows x 11 columns]

In [9]:
a1_reduced=a1[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
a1_reduced

Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
0         3    1  34.5      0      0    7.8292         3
1         3    2  47.0      1      0    7.0000         1
2         2    1  62.0      0      0    9.6875         3
3         3    1  27.0      0      0    8.6625         1
4         3    2  22.0      1      1   12.2875         1
..      ...  ...   ...    ...    ...       ...       ...
413       3    1  30.0      0      0    8.0500         1
414       1    2  39.0      0      0  108.9000         2
415       3    1  38.5      0      0    7.2500         1
416       3    1  30.0      0      0    8.0500         1
417       3    1  30.0      1      1   22.3583         2

[418 rows x 7 columns]

In [10]:
a1_reduced_data=np.array(a1_reduced)
a1_reduced_data

array([[ 3.    ,  1.    , 34.5   , ...,  0.    ,  7.8292,  3.    ],
       [ 3.    ,  2.    , 47.    , ...,  0.    ,  7.    ,  1.    ],
       [ 2.    ,  1.    , 62.    , ...,  0.    ,  9.6875,  3.    ],
       ...,
       [ 3.    ,  1.    , 38.5   , ...,  0.    ,  7.25  ,  1.    ],
       [ 3.    ,  1.    , 30.    , ...,  0.    ,  8.05  ,  1.    ],
       [ 3.    ,  1.    , 30.    , ...,  1.    , 22.3583,  2.    ]])

In [11]:
rfc=RandomForestClassifier(random_state=14,max_depth=7)
rfc.fit(data,y)
prediction=rfc.predict(a1_reduced_data)
prediction

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [12]:
PassengerId=np.arange(892,1310,1).reshape(-1,1)
PassengerId
result=np.hstack([PassengerId,prediction.reshape(-1,1)])


In [13]:
dict = {'PassengerId': result[:,0], 'Survived': result[:,1]} 
df = pd.DataFrame(dict,index=None)
df
  

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [14]:
age_binned=np.digitize(data[:,2],bins=np.array([0,12,18,35,50,70,100]))
fare_binned=np.digitize(data[:,5],bins=np.array([0,15,40,70,100,200,300,400,550]))


In [15]:
data_binned_a=np.hstack([data[:,0:2],age_binned.reshape(-1,1),data[:,3:5],fare_binned.reshape(-1,1),data[:,6].reshape(-1,1)])

In [16]:
data_binned_a

array([[3., 1., 3., ..., 0., 1., 1.],
       [1., 2., 4., ..., 0., 4., 2.],
       [3., 2., 3., ..., 0., 1., 1.],
       ...,
       [3., 2., 3., ..., 2., 2., 1.],
       [1., 1., 3., ..., 0., 2., 2.],
       [3., 1., 3., ..., 0., 1., 3.]])

In [17]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
ohe.fit(data_binned_a)
data_binned_encoded_a=ohe.transform(data_binned_a).toarray()


In [18]:
data_binned_encoded_a

array([[0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 1.]])

In [19]:
data_binned_encoded_a.shape

(891, 35)

In [20]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression(random_state=13,max_iter=10000,penalty='l2',C=1,solver='lbfgs')
scores = cvs(logreg,data,y,cv=kf)
print(scores)
print(scores.mean())

[0.81111111 0.83146067 0.82022472 0.75280899 0.88764045 0.71910112
 0.73033708 0.79775281 0.78651685 0.83146067]
0.7968414481897628


In [21]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(random_state=25,max_iter=10000)
mlp.fit(X_train,y_train)
print(mlp.score(X_train,y_train))
print(mlp.score(X_test,y_test))

0.8203592814371258
0.820627802690583


In [22]:

X_train, X_test, y_train, y_test = tts(data_binned_encoded_a, y, random_state=20,stratify=y)
mlp=MLPClassifier(random_state=25,max_iter=10000,learning_rate_init=0.001,activation='tanh',solver='adam')
mlp.fit(X_train,y_train)
print(mlp.score(X_train,y_train))
print(mlp.score(X_test,y_test))

0.875748502994012
0.8161434977578476


In [23]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=3,interaction_only=True, include_bias=False)
poly_d=poly.fit_transform(data_binned_encoded_a)
poly_d.shape

(891, 7175)

In [24]:
X_train, X_test, y_train, y_test = tts(poly_d, y, random_state=20,stratify=y)
mlp=MLPClassifier(random_state=25,max_iter=10000,learning_rate_init=0.001,activation='tanh',solver='adam')
mlp.fit(X_train,y_train)
print(mlp.score(X_train,y_train))
print(mlp.score(X_test,y_test))

0.8817365269461078
0.8251121076233184


In [25]:
from sklearn.svm import SVC
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100],
                  'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
X_train, X_test, y_train, y_test = tts(data, y, random_state=20,stratify=y)
svc=SVC(random_state=25)
svc.fit(X_train,y_train)
print(svc.score(X_train,y_train))
print(svc.score(X_test,y_test))

0.6691616766467066
0.7085201793721974


In [26]:
from sklearn.model_selection import GridSearchCV 
grid_search = GridSearchCV(svc, param_grid, cv=10)
grid_search.fit(X_train, y_train)
print(grid_search.score(X_test, y_test))

0.8295964125560538


In [27]:
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Best parameters: {'C': 100, 'gamma': 0.001}
Best cross-validation score: 0.79


In [28]:
print("Best estimator:\n{}".format(grid_search.best_estimator_))

Best estimator:
SVC(C=100, gamma=0.001, random_state=25)


In [29]:
age_binned=np.digitize(a1_reduced_data[:,2],bins=np.array([0,16,45,100]))
fare_binned=np.digitize(a1_reduced_data[:,5],bins=np.array([0,15,40,70,100,200,300,400,550]))
data_binned_a1=np.hstack([a1_reduced_data[:,0:2],age_binned.reshape(-1,1),a1_reduced_data[:,3:5],fare_binned.reshape(-1,1),a1_reduced_data[:,6].reshape(-1,1)])


In [30]:
data_binned_a1

array([[3., 1., 2., ..., 0., 1., 3.],
       [3., 2., 3., ..., 0., 1., 1.],
       [2., 1., 3., ..., 0., 1., 3.],
       ...,
       [3., 1., 2., ..., 0., 1., 1.],
       [3., 1., 2., ..., 0., 1., 1.],
       [3., 1., 2., ..., 1., 2., 2.]])

In [31]:
result=np.hstack([PassengerId,prediction.reshape(-1,1)])

dict = {'PassengerId': result[:,0], 'Survived': result[:,1]} 
df = pd.DataFrame(dict,index=None)
df

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [32]:
#df.to_csv(r"/Users/vijay/Downloads/titanic (1)/result.csv",index=False)

In [33]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(data, y, random_state=20,stratify=y)
rfc=RandomForestClassifier(random_state=14,max_depth=4)
rfc.fit(X_train,y_train)
test_score=rfc.score(X_test,y_test)
train_score=rfc.score(X_train,y_train)
print(train_score)
print(test_score)

0.8323353293413174
0.8475336322869955


In [34]:
prediction=rfc.predict(a1_reduced_data)

In [35]:
result=np.hstack([PassengerId,prediction.reshape(-1,1)])

dict = {'PassengerId': result[:,0], 'Survived': result[:,1]} 
df = pd.DataFrame(dict,index=None)
df

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [36]:
#df.to_csv(r"/Users/vijay/Downloads/titanic (1)/result.csv",index=False)

In [37]:
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier(random_state=10,max_depth=2,learning_rate=0.2, n_estimators=100,min_samples_split=4,
                              min_samples_leaf=1,max_features=1)
gbc.fit(X_train,y_train)
train_score=gbc.score(X_train,y_train)
test_score=gbc.score(X_test,y_test)
print(train_score)
print(test_score)

0.844311377245509
0.852017937219731


In [38]:
prediction=gbc.predict(a1_reduced_data)
result=np.hstack([PassengerId,prediction.reshape(-1,1)])
dict = {'PassengerId': result[:,0], 'Survived': result[:,1]} 
df = pd.DataFrame(dict,index=None)
#df.to_csv(r"/Users/vijay/Downloads/titanic (1)/result.csv",index=False)

In [39]:
scores = cvs(gbc,data,y,cv=kf)
print(scores)
print(scores.mean())

[0.8        0.84269663 0.83146067 0.74157303 0.85393258 0.75280899
 0.71910112 0.79775281 0.83146067 0.85393258]
0.8024719101123596


In [40]:
param_grid = {'max_depth': [2,3,4],
              'learning_rate': [0.1,0.2],
              'n_estimators': [ 50, 100, 150],
              'min_samples_split': [3,4,5],
              'min_samples_leaf': [1,2],
              'max_features': [1,2]}
gbc=GradientBoostingClassifier()
grid_search = GridSearchCV(gbc, param_grid, cv=5)
grid_search.fit(X_train, y_train)
print(grid_search.score(X_test, y_test))

0.8475336322869955


In [41]:
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Best parameters: {'learning_rate': 0.1, 'max_depth': 4, 'max_features': 2, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 50}
Best cross-validation score: 0.83


In [42]:
print("Best estimator:\n{}".format(grid_search.best_estimator_))

Best estimator:
GradientBoostingClassifier(max_depth=4, max_features=2, min_samples_leaf=2,
                           min_samples_split=5, n_estimators=50)


In [43]:
gbc=GradientBoostingClassifier(max_depth=4, max_features=2, min_samples_split=3,
                           n_estimators=50,learning_rate=0.1)
gbc.fit(X_train, y_train)
prediction=gbc.predict(a1_reduced_data)

In [44]:
result=np.hstack([PassengerId,prediction.reshape(-1,1)])
dict = {'PassengerId': result[:,0], 'Survived': result[:,1]} 
df = pd.DataFrame(dict,index=None)
#df.to_csv(r"/Users/vijay/Downloads/titanic (1)/result.csv",index=False)

In [45]:
X_train, X_test, y_train, y_test = tts(data_binned_a, y, random_state=20,stratify=y)
param_grid = {'max_depth': [2,3,4],
              'learning_rate': [0.1,0.2],
              'n_estimators': [ 50, 100, 150],
              'min_samples_split': [3,4,5],
              'min_samples_leaf': [1,2],
              'max_features': [1,2]}
gbc=GradientBoostingClassifier()
grid_search = GridSearchCV(gbc, param_grid, cv=5)
grid_search.fit(X_train, y_train)
print(grid_search.score(X_test, y_test))
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))
print("Best estimator:\n{}".format(grid_search.best_estimator_))

0.8340807174887892
Best parameters: {'learning_rate': 0.1, 'max_depth': 2, 'max_features': 2, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 150}
Best cross-validation score: 0.82
Best estimator:
GradientBoostingClassifier(max_depth=2, max_features=2, min_samples_leaf=2,
                           min_samples_split=5, n_estimators=150)


In [46]:
X_train, X_test, y_train, y_test = tts(data, y, random_state=20,stratify=y)
gbc=GradientBoostingClassifier(random_state=10,max_depth=2,learning_rate=0.2, n_estimators=100,min_samples_split=4,
                              min_samples_leaf=2,max_features=1)
gbc.fit(X_train,y_train)
train_score=gbc.score(X_train,y_train)
test_score=gbc.score(X_test,y_test)
print(train_score)
print(test_score)

0.8547904191616766
0.8475336322869955


In [47]:
prediction=gbc.predict(a1_reduced_data)
result=np.hstack([PassengerId,prediction.reshape(-1,1)])
dict = {'PassengerId': result[:,0], 'Survived': result[:,1]} 
df = pd.DataFrame(dict,index=None)
df.to_csv(r"/Users/vijay/Downloads/titanic (1)/result.csv",index=False)

In [48]:
# End of project
# Support vector with some parameter tuning
# and gradient_boost with some parameter tuning gives highest score 

In [49]:
# But some feature engineering is required like 

#handling missing age values
#prefixes like Master/Mr./Miss/Mrs
#can we extract information from ticket number e.g tickets bought together


